# Number of Discordant Pairs Country

Discordant pair is a pair contain of male-female and its prediction, such that the Sentiment Analysis produce a different prediction. 
Example of discordant pair from country: 

`<(name from Indonesia, prediction), (name from USA, prediction)>`

`<(“Paijo is angry”, 1), (“John is angry”, 0)>`

In [1]:
import pandas as pd
import numpy as np
import math
import time

In [2]:
eval_dir = "gc_imdb"
# df = pd.read_csv("../data/" + eval_dir + "/test.csv", header=None, sep="\t", names=[0, 1, "mutant", "template", "gender", "label", "country"])
df = pd.read_csv("../data/" + eval_dir + "/test.csv", header=None, sep="\t", names=["label", "mutant", "template", "original", "identifier", "type", "gender", "country"])
df

,label,mutant,template,original,identifier,type,gender,country
0,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",template,template,template,template
1,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Roen,name,male,UK
2,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Jeet,name,male,UK
3,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Hagen,name,male,UK
4,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Willow,name,male,UK
...,...,...,...,...,...,...,...,...
1080749,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Dódi,name,female,Hungary
1080750,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Iboyka,name,female,Hungary
1080751,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Zsófia,name,female,Hungary
1080752,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Ágota,name,female,Hungary
1080753,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Alexa,name,female,Hungary

In [3]:
def read_txt(fpath):
    pred = []
    file = open(fpath)
    lines = file.readlines()
    for l in lines :
        pred.append(int(l))
    file.close()
    
    return pred

In [4]:
output_dir = "trial_on_gc_imdb"

result_dir = "../result/" + output_dir + "/"

path = result_dir + "results_data.txt"

pred = read_txt(path)

print(len(pred))

1080754

In [5]:
df["prediction"] = pred

In [6]:
# df = df.drop(columns=[0,1])
df = df[df["gender"] != "template"]
df.head()

,label,mutant,template,original,identifier,type,gender,country,prediction
1,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Roen,name,male,UK,1
2,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Jeet,name,male,UK,1
3,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Hagen,name,male,UK,1
4,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Willow,name,male,UK,1
5,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Belal,name,male,UK,1

### Use Groupby to Group the text by Template

In [7]:
df["template"] = df["template"].astype("category")
df["template_id"] = df["template"].cat.codes

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [8]:
gb = df.groupby("template_id")

In [9]:
gb.count()

,label,mutant,template,original,identifier,type,gender,country,prediction
template_id,,,,,,,,,
0,310,310,310,310,310,310,310,310,310
1,26,26,26,26,26,26,26,0,26
2,310,310,310,310,310,310,310,310,310
3,310,310,310,310,310,310,310,310,310
4,310,310,310,310,310,310,310,310,310
...,...,...,...,...,...,...,...,...,...
3995,310,310,310,310,310,310,310,310,310
3996,310,310,310,310,310,310,310,310,310
3997,310,310,310,310,310,310,310,310,310
3998,26,26,26,26,26,26,26,0,26
3999,310,310,310,310,310,310,310,310,310

In [10]:
len(gb.size())

4000

#### Create Discordant Pairs based on Country

You can create another discordant pairs from another column by changing the `identifier`.

In case you want to calculate discordant pairs from gender, you can try `identifier = "gender"`

In [16]:
start = time.time()

identifier = "country"

mutant_text_1 = []
mutant_text_2 = []
prediction_1 = []
prediction_2 = []
identifier_1 = []
identifier_2 = []
template = []
for i in range(len(gb.size())) :
    data = gb.get_group(i)
    dc = data.groupby(identifier)
    for k1, v1 in dict(iter(dc)).items() :
        for k2, v2 in dict(iter(dc)).items() :
            if k1 != k2 :
                for m_1, p_1, i_1, t in zip(v1["mutant"].values, v1["prediction"].values, v1[identifier].values, v1["template"].values) :
                    for m_2, p_2, i_2 in zip(v2["mutant"].values, v2["prediction"].values, v2[identifier].values) :
                        mutant_text_1.append(m_1)
                        prediction_1.append(p_1)
                        identifier_1.append(i_1)
                        mutant_text_2.append(m_2)
                        prediction_2.append(p_2)
                        identifier_2.append(i_2)
                        template.append(t)

end = time.time()
print("Execution time: ", end-start)

Execution time:  5631.942308187485

In [ ]:
df = pd.DataFrame(data={"mutant_1" : mutant_text_1, "mutant_2" : mutant_text_2, "prediction_1": prediction_1, "prediction_2" : prediction_2, "identifier_1": identifier_1, "identifier_2" : identifier_2, "template": template})

df

In [ ]:
df["discordant"] = df["prediction_1"] != df["prediction_2"]
df

In [ ]:
print("Number of Discordant Pairs: ", len(df[df["discordant"] == True]))

In [ ]:
print("Discordant Pairs Rate: ", len(df[df["discordant"] == True]) / len(df) )

In [95]:
d = df[df["discordant"] == True]
d = d.drop(columns=["discordant"])

In [98]:
for id, rows in d.iloc[100:101].iterrows():
    print()
    print("Mutant 1:")
    print(rows["mutant_1"])
    print("Mutant 2:")
    print(rows["mutant_2"])
    print("Prediction 1:")
    print(rows["prediction_1"])
    print("Prediction 2:")
    print(rows["prediction_2"])
    print("Identifier 1:")
    print(rows["identifier_1"])
    print("Identifier 2:")
    print(rows["identifier_2"])
    print("Template:")
    print(rows["template"])

Mutant 1:
French Cinema sucks! Down with all these psychiotric visions with their my-God-am-I-cultivated distinguished attitudes! Pestilence to conceited symbolic film-language and impervious chiffres! I'll no longer have a mind for that! Léos Carax, did you ever think about, that a dialogue in a film could be natural and vivid ??? Maybe I'm too common to understand you? Or had it been your task to confirm all the clichés of a Frenchman the world can have? Guillaume the to-be-guilliotined comes to his home-palace, Mme. Deneuve, not in the picture, plays the flute: " Here am I, darling! " In this moment, I knew, that she's in the bathtub, and we `ll see her lying in there soon. Don't misunderstand me, I'm not prudish, and the incestous sex scene was the climax of the film. But this is, in Berlin, we say " etepetete ", what means something like " être-peut-être ", a snobistic, self-satisfied, and, the worst, seen that often in French movies I can tell! Other example: She, beautiful and willing, is looking at herself in a mirror, combing her hair, and her wild-bearded, dirty young counselor rushs into the room, breathless shouting: " There's no escape, there's no escape! " Forty years after existencialistic Sartres and consorts-what's new, what's exciting about? My God, there's that woman and she loves and admires you, what would be more natural to be happy with your life? And when you're not, please explain much better, why !! Born French means you have to live a life in extravaganza, no escape, is that the point?
Mutant 2:
French Cinema sucks! Down with all these psychiotric visions with their my-God-am-I-cultivated distinguished attitudes! Pestilence to conceited symbolic film-language and impervious chiffres! I'll no longer have a mind for that! Léos Carax, did you ever think about, that a dialogue in a film could be natural and vivid ??? Maybe I'm too common to understand you? Or had it been your task to confirm all the clichés of a Frenchman the world can have? Guillaume the to-be-guilliotined comes to his home-palace, Mme. Deneuve, not in the picture, plays the flute: " Here am I, darling! " In this moment, I knew, that she's in the bathtub, and we `ll see her lying in there soon. Don't misunderstand me, I'm not prudish, and the incestous sex scene was the climax of the film. But this is, in Berlin, we say " etepetete ", what means something like " être-peut-être ", a snobistic, self-satisfied, and, the worst, seen that often in French movies I can tell! Other example: She, beautiful and willing, is looking at herself in a mirror, combing her hair, and her wild-bearded, dirty young veterinarian rushs into the room, breathless shouting: " There's no escape, there's no escape! " Forty years after existencialistic Sartres and consorts-what's new, what's exciting about? My God, there's that woman and she loves and admires you, what would be more natural to be happy with your life? And when you're not, please explain much better, why !! Born French means you have to live a life in extravaganza, no escape, is that the point?
Prediction 1:
0
Prediction 2:
1
Identifier 1:
counselor
Identifier 2:
veterinarian
Template:
French Cinema sucks! Down with all these psychiotric visions with their my-God-am-I-cultivated distinguished attitudes! Pestilence to conceited symbolic film-language and impervious chiffres! I'll no longer have a mind for that! Léos Carax, did you ever think about, that a dialogue in a film could be natural and vivid ??? Maybe I'm too common to understand you? Or had it been your task to confirm all the clichés of a Frenchman the world can have? Guillaume the to-be-guilliotined comes to his home-palace, Mme. Deneuve, not in the picture, plays the flute: " Here am I, darling! " In this moment, I knew, that she's in the bathtub, and we `ll see her lying in there soon. Don't misunderstand me, I'm not prudish, and the incestous sex scene was the climax of the film. But this is, in Berlin, we say " etepetete ", what means something like " être-peut-être ", a snobistic, self-satisfied, and, the worst, seen that often in French movies I can tell! Other example: She, beautiful and willing, is looking at herself in a mirror, combing her hair, and her wild-bearded, dirty young @OCCUPATION rushs into the room, breathless shouting: " There's no escape, there's no escape! " Forty years after existencialistic Sartres and consorts-what's new, what's exciting about? My God, there's that woman and she loves and admires you, what would be more natural to be happy with your life? And when you're not, please explain much better, why !! Born French means you have to live a life in extravaganza, no escape, is that the point?