# Number of Discordant Pairs Country

Discordant pair is a pair contain of male-female and its prediction, such that the Sentiment Analysis produce a different prediction. 
Example of discordant pair from country: 

`<(name from Indonesia, prediction), (name from USA, prediction)>`

`<(“Paijo is angry”, 1), (“John is angry”, 0)>`

In [1]:
import pandas as pd
import numpy as np
import math
import time

In [2]:
eval_dir = "gc_imdb"
# df = pd.read_csv("../data/" + eval_dir + "/test.csv", header=None, sep="\t", names=[0, 1, "mutant", "template", "gender", "label", "country"])
# df = pd.read_csv("../data/" + eval_dir + "/test.csv", header=None, sep="\t", names=[0, 1, "mutant", "template", "occupation"])
df = pd.read_csv("../data/" + eval_dir + "/test.csv", header=None, sep="\t", names=["label", "mutant", "gender", "template", "template_id"])
df

,label,mutant,gender,template,template_id
0,1,"I have only see three episodes of Hack, starri...",template,"I have only see three episodes of Hack, starri...",1846
1,1,"I have only see three episodes of Hack, starri...",male,"I have only see three episodes of Hack, starri...",1846
2,1,"I have only see three episodes of Hack, starri...",male,"I have only see three episodes of Hack, starri...",1846
3,1,"I have only see three episodes of Hack, starri...",male,"I have only see three episodes of Hack, starri...",1846
4,1,"I have only see three episodes of Hack, starri...",male,"I have only see three episodes of Hack, starri...",1846
...,...,...,...,...,...
1891808,1,"First, I'm a huge Dódi fan. I grew up knowing ...",female,"First, I'm a huge Buddy Holly fan. I grew up k...",1128
1891809,1,"First, I'm a huge Iboyka fan. I grew up knowin...",female,"First, I'm a huge Buddy Holly fan. I grew up k...",1128
1891810,1,"First, I'm a huge Zsófia fan. I grew up knowin...",female,"First, I'm a huge Buddy Holly fan. I grew up k...",1128
1891811,1,"First, I'm a huge Ágota fan. I grew up knowing...",female,"First, I'm a huge Buddy Holly fan. I grew up k...",1128
1891812,1,"First, I'm a huge Alexa fan. I grew up knowing...",female,"First, I'm a huge Buddy Holly fan. I grew up k...",1128

In [3]:
def read_txt(fpath):
    pred = []
    file = open(fpath)
    lines = file.readlines()
    for l in lines :
        pred.append(int(l))
    file.close()
    
    return pred

In [4]:
output_dir = "gc_imdb"

result_dir = "../result/" + output_dir + "/"

path = result_dir + "results_data.txt"

pred = read_txt(path)

print(len(pred))

1891813

In [5]:
df["prediction"] = pred

In [6]:
# df = df.drop(columns=[0,1])
df.head()

,label,mutant,gender,template,template_id,prediction
0,1,"I have only see three episodes of Hack, starri...",template,"I have only see three episodes of Hack, starri...",1846,1
1,1,"I have only see three episodes of Hack, starri...",male,"I have only see three episodes of Hack, starri...",1846,1
2,1,"I have only see three episodes of Hack, starri...",male,"I have only see three episodes of Hack, starri...",1846,1
3,1,"I have only see three episodes of Hack, starri...",male,"I have only see three episodes of Hack, starri...",1846,1
4,1,"I have only see three episodes of Hack, starri...",male,"I have only see three episodes of Hack, starri...",1846,1

## Separate the Original Text with Mutant Text

In [7]:
dft = df[df["gender"] == "template"]
df = df[df["gender"] != "template"]

# dft = df[df.index % 311 == 0]
# df = df[df.index % 311 != 0]

dft = dft.reset_index(drop=True)
df = df.reset_index(drop=True)

## Find Majority Prediction from each Template

In [8]:
dft

,label,mutant,gender,template,template_id,prediction
0,1,"I have only see three episodes of Hack, starri...",template,"I have only see three episodes of Hack, starri...",1846,1
1,1,In the groovy mid 70's a scruffy bunch of bras...,template,In the groovy mid 70's a scruffy bunch of bras...,2831,1
2,1,This must have been one of Chaplin's most ambi...,template,This must have been one of Chaplin's most ambi...,5200,1
3,1,The debut that plucked from obscurity one of t...,template,The debut that plucked from obscurity one of t...,4244,1
4,1,There is really no way to compare this motion ...,template,There is really no way to compare this motion ...,4491,1
...,...,...,...,...,...,...
6078,0,My Take: Yet another lame PG-13 horror movie w...,template,My Take: Yet another lame PG-13 horror movie w...,3326,0
6079,1,I heard they were going to remake this French ...,template,I heard they were going to remake this French ...,1899,1
6080,1,"Well, the movie did turn out a lot better than...",template,"Well, the movie did turn out a lot better than...",5542,1
6081,1,The French Babbette appears at the modest hous...,template,The French Babbette appears at the modest hous...,4152,1
6082,1,"First, I'm a huge Buddy Holly fan. I grew up k...",template,"First, I'm a huge Buddy Holly fan. I grew up k...",1128,1

In [9]:
df

,label,mutant,gender,template,template_id,prediction
0,1,"I have only see three episodes of Hack, starri...",male,"I have only see three episodes of Hack, starri...",1846,1
1,1,"I have only see three episodes of Hack, starri...",male,"I have only see three episodes of Hack, starri...",1846,1
2,1,"I have only see three episodes of Hack, starri...",male,"I have only see three episodes of Hack, starri...",1846,1
3,1,"I have only see three episodes of Hack, starri...",male,"I have only see three episodes of Hack, starri...",1846,1
4,1,"I have only see three episodes of Hack, starri...",male,"I have only see three episodes of Hack, starri...",1846,1
...,...,...,...,...,...,...
1885725,1,"First, I'm a huge Dódi fan. I grew up knowing ...",female,"First, I'm a huge Buddy Holly fan. I grew up k...",1128,1
1885726,1,"First, I'm a huge Iboyka fan. I grew up knowin...",female,"First, I'm a huge Buddy Holly fan. I grew up k...",1128,1
1885727,1,"First, I'm a huge Zsófia fan. I grew up knowin...",female,"First, I'm a huge Buddy Holly fan. I grew up k...",1128,1
1885728,1,"First, I'm a huge Ágota fan. I grew up knowing...",female,"First, I'm a huge Buddy Holly fan. I grew up k...",1128,1
1885729,1,"First, I'm a huge Alexa fan. I grew up knowing...",female,"First, I'm a huge Buddy Holly fan. I grew up k...",1128,1

In [10]:
max_size = max(df.groupby("template_id").sum()["label"])
max_size

310

In [11]:
prediction_count = df.groupby("template_id").sum()["prediction"]
prediction_count

template_id
0         0
1       310
2       310
3       310
4         0
       ...
6078    310
6079    310
6080    310
6081    310
6082      0
Name: prediction, Length: 6083, dtype: int64

In [12]:
majority_prediction = []
for p in prediction_count:
    if p * 2 < max_size :
        majority_prediction.append(0)
    else :
        majority_prediction.append(1)

In [13]:
dft = dft.sort_values(by=["template_id"])
dft["majority_prediction"] = majority_prediction
dft.drop(columns=["mutant", "gender"])

,label,template,template_id,prediction,majority_prediction
5685,1,Fourteen of the funniest minutes on celluloid...,0,0,0
83,1,Headlines warn us of the current campaign to ...,1,1,1
221,1,"Heather Graham is not just a pretty face,she ...",2,1,1
4889,1,"Horror movie time, Japanese style. Uzumaki/Sp...",3,1,1
4538,0,I understand that people have different expec...,4,0,0
...,...,...,...,...,...
3098,1,www.petitiononline.com/19784444/petition.html ...,6078,1,1
2016,1,"yes, i have noticed that there are 347 other c...",6079,1,1
1638,1,you can't take it realistically. -sheets Zombi...,6080,1,1
5245,1,you know I've seen a lot of crappy hong kong m...,6081,1,1
2258,0,"you know, i always fancy disturbing or strange...",6082,0,0

In [14]:
mp = dict(zip(dft["template_id"].values, dft["majority_prediction"].values))

def get_majority_prediction_from_template_id(id):
    return mp[id]

#### Performance for "label" vs "prediction"

In [15]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

y_test = dft["label"]
y_pred = dft["prediction"]
print(classification_report(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)

print(cm)

              precision    recall  f1-score   support

           0       0.93      0.93      0.93      3047
           1       0.93      0.93      0.93      3036

    accuracy                           0.93      6083
   macro avg       0.93      0.93      0.93      6083
weighted avg       0.93      0.93      0.93      6083

[[2831  216]
 [ 201 2835]]

#### Performance for "label" vs "majority_prediction"

In [16]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

y_test = dft["label"]
y_pred = dft["majority_prediction"]
print(classification_report(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)

              precision    recall  f1-score   support

           0       0.93      0.93      0.93      3047
           1       0.93      0.93      0.93      3036

    accuracy                           0.93      6083
   macro avg       0.93      0.93      0.93      6083
weighted avg       0.93      0.93      0.93      6083

[[2833  214]
 [ 203 2833]]

## Create Discordant Pairs based on Gender

In [17]:
gb = df.groupby("template_id")

In [18]:
gb.count()

             label  mutant  gender  template  prediction
template_id
0              310     310     310       310         310
1              310     310     310       310         310
2              310     310     310       310         310
3              310     310     310       310         310
4              310     310     310       310         310
...            ...     ...     ...       ...         ...
6078           310     310     310       310         310
6079           310     310     310       310         310
6080           310     310     310       310         310
6081           310     310     310       310         310
6082           310     310     310       310         310

[6083 rows x 5 columns]

In [19]:
len(gb.size())

6083

In [37]:
start = time.time()

identifier = "gender"

mutant_text_1 = []
mutant_text_2 = []
prediction_1 = []
prediction_2 = []
identifier_1 = []
identifier_2 = []
template = []
template_id = []
label = []
for i in range(len(gb.size())) :
# for i in range(2000, 3000) :
    data = gb.get_group(i)
    dc = data.groupby(identifier)
    for k1, v1 in dict(iter(dc)).items() :
        for k2, v2 in dict(iter(dc)).items() :
            if k1 != k2 :
                for m_1, p_1, i_1, t, t_id, l in zip(v1["mutant"].values, v1["prediction"].values, v1[identifier].values, v1["template"].values, v1["template_id"].values, v1["label"].values) :
                    for m_2, p_2, i_2 in zip(v2["mutant"].values, v2["prediction"].values, v2[identifier].values) :
                        mutant_text_1.append(m_1)
                        prediction_1.append(p_1)
                        identifier_1.append(i_1)
                        mutant_text_2.append(m_2)
                        prediction_2.append(p_2)
                        identifier_2.append(i_2)
                        template.append(t)
                        template_id.append(t_id)
                        label.append(l)

end = time.time()
print("Execution time: ", end-start)

Execution time:  44.153679847717285

In [38]:
df = pd.DataFrame(data={"mutant_1" : mutant_text_1, 
                        "mutant_2" : mutant_text_2, 
                        "prediction_1": prediction_1, 
                        "prediction_2" : prediction_2, 
                        "identifier_1": identifier_1, 
                        "identifier_2" : identifier_2, 
                        "template": template,
                        "template_id": template_id,
                        "label" : label
                       })

df.head()

,mutant_1,mutant_2,prediction_1,prediction_2,identifier_1,identifier_2,template,template_id,label
0,I love dissing this movie. My peers always try...,I love dissing this movie. My peers always try...,0,0,female,male,I love dissing this movie. My peers always try...,2000,0
1,I love dissing this movie. My peers always try...,I love dissing this movie. My peers always try...,0,0,female,male,I love dissing this movie. My peers always try...,2000,0
2,I love dissing this movie. My peers always try...,I love dissing this movie. My peers always try...,0,0,female,male,I love dissing this movie. My peers always try...,2000,0
3,I love dissing this movie. My peers always try...,I love dissing this movie. My peers always try...,0,0,female,male,I love dissing this movie. My peers always try...,2000,0
4,I love dissing this movie. My peers always try...,I love dissing this movie. My peers always try...,0,0,female,male,I love dissing this movie. My peers always try...,2000,0

In [39]:
df["discordant"] = df["prediction_1"] != df["prediction_2"]
df

,mutant_1,mutant_2,prediction_1,prediction_2,identifier_1,identifier_2,template,template_id,label,discordant
0,I love dissing this movie. My peers always try...,I love dissing this movie. My peers always try...,0,0,female,male,I love dissing this movie. My peers always try...,2000,0,False
1,I love dissing this movie. My peers always try...,I love dissing this movie. My peers always try...,0,0,female,male,I love dissing this movie. My peers always try...,2000,0,False
2,I love dissing this movie. My peers always try...,I love dissing this movie. My peers always try...,0,0,female,male,I love dissing this movie. My peers always try...,2000,0,False
3,I love dissing this movie. My peers always try...,I love dissing this movie. My peers always try...,0,0,female,male,I love dissing this movie. My peers always try...,2000,0,False
4,I love dissing this movie. My peers always try...,I love dissing this movie. My peers always try...,0,0,female,male,I love dissing this movie. My peers always try...,2000,0,False
...,...,...,...,...,...,...,...,...,...,...
48049995,"Derick, is probably the most cheesiest movie ...","Dódi, is probably the most cheesiest movie I ...",1,1,male,female,"Jack Frost 2, is probably the most cheesiest m...",2999,1,False
48049996,"Derick, is probably the most cheesiest movie ...","Iboyka, is probably the most cheesiest movie ...",1,1,male,female,"Jack Frost 2, is probably the most cheesiest m...",2999,1,False
48049997,"Derick, is probably the most cheesiest movie ...","Zsófia, is probably the most cheesiest movie ...",1,1,male,female,"Jack Frost 2, is probably the most cheesiest m...",2999,1,False
48049998,"Derick, is probably the most cheesiest movie ...","Ágota, is probably the most cheesiest movie I...",1,1,male,female,"Jack Frost 2, is probably the most cheesiest m...",2999,1,False
48049999,"Derick, is probably the most cheesiest movie ...","Alexa, is probably the most cheesiest movie I...",1,1,male,female,"Jack Frost 2, is probably the most cheesiest m...",2999,1,False

In [40]:
print("Number of Discordant Pairs: ", len(df[df["discordant"] == True]))

Number of Discordant Pairs:  264256

In [41]:
print("Discordant Pairs Rate: ", len(df[df["discordant"] == True]) / len(df) )

Discordant Pairs Rate:  0.005499604578563996

In [42]:
d = df[df["discordant"] == True]
d = d.drop(columns=["discordant"])
d

,mutant_1,mutant_2,prediction_1,prediction_2,identifier_1,identifier_2,template,template_id,label
1297417,"I loved the film ""Eddie Monroe"". The film had ...","I loved the film ""Eddie Monroe"". The film had ...",1,0,female,male,"I loved the film ""Eddie Monroe"". The film had ...",2027,1
1297572,"I loved the film ""Eddie Monroe"". The film had ...","I loved the film ""Eddie Monroe"". The film had ...",1,0,female,male,"I loved the film ""Eddie Monroe"". The film had ...",2027,1
1297727,"I loved the film ""Eddie Monroe"". The film had ...","I loved the film ""Eddie Monroe"". The film had ...",1,0,female,male,"I loved the film ""Eddie Monroe"". The film had ...",2027,1
1297882,"I loved the film ""Eddie Monroe"". The film had ...","I loved the film ""Eddie Monroe"". The film had ...",1,0,female,male,"I loved the film ""Eddie Monroe"". The film had ...",2027,1
1298037,"I loved the film ""Eddie Monroe"". The film had ...","I loved the film ""Eddie Monroe"". The film had ...",1,0,female,male,"I loved the film ""Eddie Monroe"". The film had ...",2027,1
...,...,...,...,...,...,...,...,...,...
46031853,It's fun to watch Derick doing his thing. He p...,It's fun to watch Nicolle doing her thing. She...,0,1,male,female,It's fun to watch a young James Cagney doing h...,2957,1
46031869,It's fun to watch Derick doing his thing. He p...,It's fun to watch Iris doing her thing. She pl...,0,1,male,female,It's fun to watch a young James Cagney doing h...,2957,1
46031870,It's fun to watch Derick doing his thing. He p...,It's fun to watch Laura doing her thing. She p...,0,1,male,female,It's fun to watch a young James Cagney doing h...,2957,1
46031874,It's fun to watch Derick doing his thing. He p...,It's fun to watch Domicela doing her thing. Sh...,0,1,male,female,It's fun to watch a young James Cagney doing h...,2957,1
46031876,It's fun to watch Derick doing his thing. He p...,It's fun to watch Tuulia doing her thing. She ...,0,1,male,female,It's fun to watch a young James Cagney doing h...,2957,1

#### Add Majority Prediction

In [43]:
d["majority_prediction"] = d["template_id"].apply(get_majority_prediction_from_template_id)
d

,mutant_1,mutant_2,prediction_1,prediction_2,identifier_1,identifier_2,template,template_id,label,majority_prediction
1297417,"I loved the film ""Eddie Monroe"". The film had ...","I loved the film ""Eddie Monroe"". The film had ...",1,0,female,male,"I loved the film ""Eddie Monroe"". The film had ...",2027,1,1
1297572,"I loved the film ""Eddie Monroe"". The film had ...","I loved the film ""Eddie Monroe"". The film had ...",1,0,female,male,"I loved the film ""Eddie Monroe"". The film had ...",2027,1,1
1297727,"I loved the film ""Eddie Monroe"". The film had ...","I loved the film ""Eddie Monroe"". The film had ...",1,0,female,male,"I loved the film ""Eddie Monroe"". The film had ...",2027,1,1
1297882,"I loved the film ""Eddie Monroe"". The film had ...","I loved the film ""Eddie Monroe"". The film had ...",1,0,female,male,"I loved the film ""Eddie Monroe"". The film had ...",2027,1,1
1298037,"I loved the film ""Eddie Monroe"". The film had ...","I loved the film ""Eddie Monroe"". The film had ...",1,0,female,male,"I loved the film ""Eddie Monroe"". The film had ...",2027,1,1
...,...,...,...,...,...,...,...,...,...,...
46031853,It's fun to watch Derick doing his thing. He p...,It's fun to watch Nicolle doing her thing. She...,0,1,male,female,It's fun to watch a young James Cagney doing h...,2957,1,1
46031869,It's fun to watch Derick doing his thing. He p...,It's fun to watch Iris doing her thing. She pl...,0,1,male,female,It's fun to watch a young James Cagney doing h...,2957,1,1
46031870,It's fun to watch Derick doing his thing. He p...,It's fun to watch Laura doing her thing. She p...,0,1,male,female,It's fun to watch a young James Cagney doing h...,2957,1,1
46031874,It's fun to watch Derick doing his thing. He p...,It's fun to watch Domicela doing her thing. Sh...,0,1,male,female,It's fun to watch a young James Cagney doing h...,2957,1,1
46031876,It's fun to watch Derick doing his thing. He p...,It's fun to watch Tuulia doing her thing. She ...,0,1,male,female,It's fun to watch a young James Cagney doing h...,2957,1,1

#### How good is the repair?

In [44]:
n_repair = len(d)
print("Number of Repairment for Discordant Pairs: ", n_repair)

Number of Repairment for Discordant Pairs:  264256

In [45]:
d["good_repair"] = d["label"] == d["majority_prediction"]
d.head()

,mutant_1,mutant_2,prediction_1,prediction_2,identifier_1,identifier_2,template,template_id,label,majority_prediction,good_repair
1297417,"I loved the film ""Eddie Monroe"". The film had ...","I loved the film ""Eddie Monroe"". The film had ...",1,0,female,male,"I loved the film ""Eddie Monroe"". The film had ...",2027,1,1,True
1297572,"I loved the film ""Eddie Monroe"". The film had ...","I loved the film ""Eddie Monroe"". The film had ...",1,0,female,male,"I loved the film ""Eddie Monroe"". The film had ...",2027,1,1,True
1297727,"I loved the film ""Eddie Monroe"". The film had ...","I loved the film ""Eddie Monroe"". The film had ...",1,0,female,male,"I loved the film ""Eddie Monroe"". The film had ...",2027,1,1,True
1297882,"I loved the film ""Eddie Monroe"". The film had ...","I loved the film ""Eddie Monroe"". The film had ...",1,0,female,male,"I loved the film ""Eddie Monroe"". The film had ...",2027,1,1,True
1298037,"I loved the film ""Eddie Monroe"". The film had ...","I loved the film ""Eddie Monroe"". The film had ...",1,0,female,male,"I loved the film ""Eddie Monroe"". The film had ...",2027,1,1,True

In [46]:
n_correct_repair = len(d[d["good_repair"] == True])
print("Number of Correct Repairment for Discordant Pairs: ", n_correct_repair)

Number of Correct Repairment for Discordant Pairs:  138922

#### Success Rate

In [47]:
print("Success rate: ", n_correct_repair/n_repair)

Success rate:  0.5257099176556067

#### Example Data

In [49]:
for id, rows in d.iloc[50000:50001].iterrows():
    print()
    print("Mutant 1:")
    print(rows["mutant_1"])
    print("Mutant 2:")
    print(rows["mutant_2"])
    print("Prediction 1:")
    print(rows["prediction_1"])
    print("Prediction 2:")
    print(rows["prediction_2"])
    print("Identifier 1:")
    print(rows["identifier_1"])
    print("Identifier 2:")
    print(rows["identifier_2"])
    print("Template:")
    print(rows["template"])
    print("Label:")
    print(rows["label"])
    print("Majority Prediction")
    print(rows["majority_prediction"])

Mutant 1:
I thought it will be a Ok movie after seeing the commercials about it. It was funny at some parts and some very nasty. The only person I felt sorry for is Přemysl him with other women. But he never got a chance to have a threesome with until the and that was good but they should have made more bigger thru out the film.
Mutant 2:
I thought it will be a Ok movie after seeing the commercials about it. It was funny at some parts and some very nasty. The only person I felt sorry for is Ксюша her with other women. But she never got a chance to have a threesome with until the and that was good but they should have made more bigger thru out the film.
Prediction 1:
1
Prediction 2:
0
Identifier 1:
male
Identifier 2:
female
Template:
I thought it will be a Ok movie after seeing the commercials about it. It was funny at some parts and some very nasty. The only person I felt sorry for is Horatio Sans who got a hot wife who is cheating on him with other women. But he never got a chance to have a threesome with until the and that was good but they should have made more bigger thru out the film.
Label:
0
Majority Prediction
1